version: "3"

services:
  router:
    image: traefik:v2.3
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    expose: 
      - "80"
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  testurl:
    image: containous/whoami
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testurl-router.rule=PathPrefix(`/test`)"

  nodeapi:
    build:
      context: formserver
      dockerfile: DockerfileDev
    expose:
      - "80"
    ports:
      - "1001:80"
    depends_on:
      - redisserver
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodeapi-router.rule=PathPrefix(`/node`)"
      - "traefik.http.middlewares.nodeapi-rempath.stripprefix.prefixes=/node"
      - "traefik.http.routers.nodeapi-router.middlewares=nodeapi-rempath"
  
  redisserver:
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"
  
  mysqldb: 
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "${mysql_db}"
      MYSQL_USER: "${mysql_user}"
      MYSQL_PASSWORD: "${mysql_pwd}"
      MYSQL_ROOT_PASSWORD: "${mysql_root_pwd}"
    
    ports:
      - "3306:3306"
    expose:
      - "3306"

    volumes:
      - "./.mysql-data/db:/var/lib/mysql" 
    

